services:
  - type: web
    name: tft-app-backend
    env: go
    buildCommand: cd tft-app/tft-app && go mod tidy && go build -o main .
    startCommand: cd tft-app/tft-app && ./main
    envVars:
      - key: PORT
        value: 8080
      - key: RIOT_API_KEY
        sync: false